export const blogShow_catagory = [
    {catName: "trending"},
    {catName: "SEO"},
    {catName: "Digital Marketing"},
    {catName: "Website"},
]
export const blogs_showcase = [
    {
        name:"SEO Research",
        catName: "SEO",
        blogURL: "/blogs/seo-research",
        imgUrl: "https://images.unsplash.com/photo-1600469984476-c713650f1b1b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "We manage every aspect of your social media- from content strategy, branding and images, to community engagement. We research trends and news to create content that keeps your brand current and relevant.",
    },
    {
        name:"SEO Research",
        catName: "SEO",
        blogURL: "/blogs/seo-research",
        imgUrl: "https://images.unsplash.com/photo-1600469984476-c713650f1b1b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "We manage every aspect of your social media- from content strategy, branding and images, to community engagement. We research trends and news to create content that keeps your brand current and relevant.",
    },
    {
        name:"SEO Research",
        catName: "SEO",
        blogURL: "/blogs/seo-research",
        imgUrl: "https://images.unsplash.com/photo-1600469984476-c713650f1b1b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "We manage every aspect of your social media- from content strategy, branding and images, to community engagement. We research trends and news to create content that keeps your brand current and relevant.",
    },
    {
        name:"Digital Marketing Research",
        catName: "Digital Marketing",
        blogURL: "/blogs/digital-marketing-research",
        imgUrl: "https://images.unsplash.com/photo-1694013018516-afd7bc03253e?q=80&w=2129&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "We manage every aspect of your social media- from content strategy, branding and images, to community engagement. We research trends and news to create content that keeps your brand current and relevant.",
    },
    {
        name:"Digital Marketing Research",
        catName: "Digital Marketing",
        blogURL: "/blogs/digital-marketing-research",
        imgUrl: "https://images.unsplash.com/photo-1694013018516-afd7bc03253e?q=80&w=2129&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "We manage every aspect of your social media- from content strategy, branding and images, to community engagement. We research trends and news to create content that keeps your brand current and relevant.",
    },
    {
        name:"Digital Marketing Research",
        catName: "Digital Marketing",
        blogURL: "/blogs/digital-marketing-research",
        imgUrl: "https://images.unsplash.com/photo-1694013018516-afd7bc03253e?q=80&w=2129&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "We manage every aspect of your social media- from content strategy, branding and images, to community engagement. We research trends and news to create content that keeps your brand current and relevant.",
    },
    {
        name:"website Design and Development",
        catName: "Website",
        blogURL: "/blogs/digital-marketing-research",
        imgUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "We manage every aspect of your social media- from content strategy, branding and images, to community engagement. We research trends and news to create content that keeps your brand current and relevant.",
    },
    {
        name:"website Design and Development",
        catName: "Website",
        blogURL: "/blogs/digital-marketing-research",
        imgUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "We manage every aspect of your social media- from content strategy, branding and images, to community engagement. We research trends and news to create content that keeps your brand current and relevant.",
    },
    {
        name:"website Design and Development",
        catName: "Website",
        blogURL: "/blogs/digital-marketing-research",
        imgUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "We manage every aspect of your social media- from content strategy, branding and images, to community engagement. We research trends and news to create content that keeps your brand current and relevant.",
    },
    {
        name:"Trending Design and Development",
        catName: "trending",
        blogURL: "/blogs/digital-marketing-research",
        imgUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "We manage every aspect of your social media- from content strategy, branding and images, to community engagement. We research trends and news to create content that keeps your brand current and relevant.",
    },
    {
        name:"Trending Design and Development",
        catName: "trending",
        blogURL: "/blogs/digital-marketing-research",
        imgUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "We manage every aspect of your social media- from content strategy, branding and images, to community engagement. We research trends and news to create content that keeps your brand current and relevant.",
    },
    {
        name:"Trending Design and Development",
        catName: "trending",
        blogURL: "/blogs/digital-marketing-research",
        imgUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "We manage every aspect of your social media- from content strategy, branding and images, to community engagement. We research trends and news to create content that keeps your brand current and relevant.",
    },
]